### ISSUE TITLE
Assigning crs

### ISSUE THREAD

**Issue by sarahrehman1** [sarahrehman1/R#1]
I've been trying to assign a crs to my clipped bioclim maps in R. I tried these codes to make it OSGB36: 

newcrs <- CRS("+proj=longlat +datum=OSGB36")
bio2GB <- spTransform(bio2crop, newcrs)

These didn't work, so I also tried: 

newData <- projectRaster(bio2crop, proj4string(coord)) 
This attempts to assign the bioclim maps to the same crs as my coordinates. This assumes that the coordinates are in the right crs (which I thought they were as they overlay with my GB polygon), however, error messages still come up when I use this code, which makes me think the crs is not right. If the crs is undefined, then it can't be projected. 

I'm starting to think there could be an issue within R, maybe I need to download different packages which recognise OSGB36? I attempted to just assign a new crs on its own, without attaching it to any data: 

newcrs <- CRS("+proj=longlat +datum=OSGB36") ​and newcrs <- CRS("+init=epsg:27700"). 
This still came up with errors discarding OSGB36. Maybe the issue is that R doesn't want to work with OSGB36? Though it clearly recognises it? 

Thanks!

**Comment by hartikha** [comment]
Could you add the Ines_coordinates datafile to github please?

**Comment by hartikha** [comment]
Sarah - I have added code that does achieve I think what you wanted, but assigning the datum seems impossible. the same error comes with other datums too so this is something to do with the package updates. Upshot though is that I found a way to reproject the bioclim data to 27700 and it seems to map fine. I also added a way to extract data from your bioclim layers.
