### ISSUE TITLE
Making background values 

### ISSUE THREAD

**Issue by sarahrehman1** [sarahrehman1/R#2]
In the most recent code I uploaded, I've attempted to make random background values to be used as a comparison to observe bias in my data. I've labelled the section where the background values code starts so it should be easy for you to find. 

I think I managed to make the 500 random background points, as when I head them, it presents a number of random coordinates. However, I realised that these random points may not be within the extent of the UK, so I tried to assign them within the 'coordExt'. 
This bring up the error: _Error in randomPoints(all, ext = coordExt, 10) : 
  generated random points = 0 times requested number; Use a higher value for tryf
In addition: Warning message:
In randomPoints(all, ext = coordExt, 10) :
  changed n to ncell of the mask (extent)_
I tried to add a tryf to multiply my actual species occurrence records and increase example sample size, however I don't think it worked. I read somewhere that the error may occur if the extent is too small, but even when I make the random points '1', it still doesn't work. 

I need the random background points in order to run some of the main steps in SDM, so if you have any ideas it would be greatly appreciated!

**Comment by hartikha** [comment]
Hi Sarah - I think I have fixed the problem - I think there was just a coding error, referring to a wrong  output. make sure you have have installed library "ecospat" and "colorRamps"
install.packages("ecospat")
install.packages("colorRamps")
library(ecospat)
library(colorRamps)

you should see the changes in mycode file - this runs up to line 271 before you move into maxent models
