### ISSUE TITLE
loading adf file

### ISSUE THREAD

**Issue by sarahrehman1** [sarahrehman1/R#3]
The human influence index data is in adf format rather than shapefile, so I'm struggling to load it into R. I've committed the files to github, with some code that I was testing. I'm not sure if you'll need more of the data, but I downloaded the 'Europe' file from this website if you need it: https://sedac.ciesin.columbia.edu/data/set/wildareas-v2-human-influence-index-geographic/data-download. 

As it is an adf, the data is in raster format rather than vector, which is different to the rest of my data (coordinates and gb shapefile) - do you think this will be a problem when stacking the files?

**Comment by hartikha** [comment]
I will close this as it is sort of solved. any further issues, let me know
